### ISSUE TITLE
Remove underscores from template names

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/generator-ng2-alfresco-component#16]
For the moment one needs to rename files (to get underscore prefix) or map them (i.e. index.ts -> _barrelFile.ts). The larger project structure the more time needed to mess with file names when keeping it up-to-date.

Template file names should reflect real file names to greatly reduce maintenance efforts and support copy-pasting of files where applicable.

**Comment by eromano** [comment]
Denys usually in all the yeoman project the template files have this type of convention

**Comment by DenisVuyka** [comment]
Removing underscores greatly improves the speed of updating files' content regardless of the conventions used out there. What is the main reason for underscores? Do they help with anything at all?
