### ISSUE TITLE
Generator hangs

### ISSUE THREAD

**Issue by MartinDoyleUK** [Alfresco/generator-ng2-alfresco-component#2]
When running the generator (component name chosen was "component"), it hangs after choosing the name. Having spoken to Eugenio, it seems likely that this is due to a clash with an existing NPM package name. Choosing a very unique name works fine.

**Comment by eromano** [comment]
Thanks @MartinDoyleUK I'll fix the issue in the 0.0.25 release . I am sadly going to remove this cool functionality is not stable
