### ISSUE TITLE
Angular Cli documentation makes no sense

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/generator-ng2-alfresco-component#24]
Usage of Angular CLI has nothing to do with component project generation. It is a point of a separate documentation or blog post rather than putting that into yeoman generator readme.

Expected result: unrelated angular cli commands and additional global installations should be removed from readme.

**Comment by magemello** [comment]
I would prefer have some conversation before removing the support for the angular cli....

**Comment by DenisVuyka** [comment]
Restored angular cli support, closing this ticket as invalid.

**Comment by magemello** [comment]
Thank you, Denys
