### ISSUE TITLE
App Generation fails when no DocList is provided 

### ISSUE THREAD

**Issue by doug4j** [Alfresco/generator-ng2-alfresco-component#37]
[yo ng2-alfresco-app.txt](https://github.com/Alfresco/generator-ng2-alfresco-component/files/644118/yo.ng2-alfresco-app.txt)
[npm start.txt](https://github.com/Alfresco/generator-ng2-alfresco-component/files/644119/npm.start.txt)

**Comment by doug4j** [comment]
This is likely related to #35

**Comment by eromano** [comment]
This bug is for the app generator  https://github.com/Alfresco/generator-ng2-alfresco-app

**Comment by doug4j** [comment]
Thanks.
